### ISSUE TITLE
validates_acceptance_of :terms_of_service failing

### ISSUE THREAD

**Issue by nathanstruhs** [osu-cascades/tracing-resilience#14]
Validation always fails even if the param value of :terms_of_service is '1' (validates_acceptance_of expects 0 or 1, or true/false values)
Was working until I introduced new user attributes (name, phone, state, etc..)

**Comment by ybakos** [comment]
@nathanstruhs Will look into this.

**Comment by ybakos** [comment]
@nathanstruhs The Rails documentation makes it a little hard to infer the behavior:

"This should be set to, or include, true if you are validating a database column ..."

Since we are not validating an attribute that is persisted to the DB, we should not use the `accept: true` option.

By default, the allowable values for a 'virtual' attribute like `terms_of_service` are `'1'` or `true`. Which is what you want, right out of the box, since a checkbox value param has the string value `'1'`.

**Comment by ybakos** [comment]
http://api.rubyonrails.org/v5.2.0/classes/ActiveModel/Validations/HelperMethods.html#method-i-validates_acceptance_of

we also don't need to create the attribute with an `attr_accessor` declaration.
